---
name: Cloud Run Function - Annict Subscription Scraper
env:
  ANNICT_TEST_WORK_ID: 10976 # https://annict.com/works/10976 でテスト
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-cloudrun-function:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Auth with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GOOGLE_PJ_NO }}/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "gcp-cloud-run-private@${{ secrets.GOOGLE_PJ_ID }}.iam.gserviceaccount.com"

      - name: Deploy CloudRun Function
        uses: google-github-actions/deploy-cloud-functions@v3
        timeout-minutes: 10
        with:
          name: annict-subscription-scraper
          source_dir: ./annict-subscription-scraper
          runtime: go122
          region: asia-northeast1
          memory_mb: 128 # MB
          entry_point: main
          timeout: 60 # seconds

      - name: Test
        run: |
          response=$(curl "http://${{ steps.deploy.outputs.url }}:8080/?id=${{ env.ANNICT_TEST_WORK_ID }}")
          result=$(echo $response | jq '.services[] | select(.name == "dアニメストア") | .available')
          if [[ $result == "true" ]]; then
            echo "The return value is true."
          else
            echo "The return value is not true."
            exit 1
          fi
