name: Deploy to magic mirror

env:
  GCP_CLOUDRUN_NAME: magic-mirror-server
  BASE_DOCKER_IMAGE: karsten13/docker-magicmirror
  DOCKER_COMPOSE_PATH: magic-mirror-server/docker-compose.yml
  CUSTOM_CONTAINER_REGISTRY: ghcr.io

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  magic-mirror-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CUSTOM_CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CUSTOM_CONTAINER_REGISTRY }}/${{ github.actor }}/magic-mirror-server
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          file: ./magic-mirror-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push container image as latest
        uses: docker/build-push-action@v5
        with:
          file: ./magic-mirror-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: latest

  magic-mirror-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
    
      - name: Azure authentication
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Prepare environment variables
        run: |
          export CUSTOM_CONTAINER_REGISTRY=${{ env.CUSTOM_CONTAINER_REGISTRY }}
          export GITHUB_ACTOR=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          export OPEN_WEATHER_MAP_LOCATION=${{ secrets.OPEN_WEATHER_MAP_LOCATION }}
          export OPEN_WEATHER_MAP_LOCATION_ID=${{ secrets.OPEN_WEATHER_MAP_LOCATION_ID }}
          export OPEN_WEATHER_MAP_API_KEY=${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
          export CALENDAR_ICS_URL_PATH=${{ secrets.CALENDAR_ICS_URL_PATH }}
        shell: bash

      - name: Generate docker-compose.yml
        run: |
          envsubst < ${{ env.DOCKER_COMPOSE_PATH }} > ${{ env.DOCKER_COMPOSE_PATH }}.azure

      - name: Deploy to Azure Web App for Container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.GCP_CLOUDRUN_NAME }}
          images: ${{ env.CUSTOM_CONTAINER_REGISTRY }}/${GITHUB_ACTOR}magic-mirror-server
          configuration-file: ${{ env.DOCKER_COMPOSE_PATH }}.azure

    # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
