name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - '"main"'

env:
  PROJECT_ID: 'my-project' # TODO: update to your Google Cloud project ID
  REGION: 'us-central1' # TODO: update to your region
  SERVICE: 'my-service' # TODO: update to your service name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider' # TODO: update to your workload identity provider

jobs:
  magic-mirror-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CUSTOM_CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CUSTOM_CONTAINER_REGISTRY }}/${{ github.actor }}/magic-mirror-server
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          file: ./magic-mirror-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push container image as latest
        uses: docker/build-push-action@v5
        with:
          file: ./magic-mirror-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: latest

  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Prepare environment variables
        run: |
          export CUSTOM_CONTAINER_REGISTRY=${{ env.CUSTOM_CONTAINER_REGISTRY }}
          export GITHUB_ACTOR=${{ github.actor }}
          export OPEN_WEATHER_MAP_LOCATION=${{ secrets.OPEN_WEATHER_MAP_LOCATION }}
          export OPEN_WEATHER_MAP_LOCATION_ID=${{ secrets.OPEN_WEATHER_MAP_LOCATION_ID }}
          export OPEN_WEATHER_MAP_API_KEY=${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
          export CALENDAR_ICS_URL_PATH=${{ secrets.CALENDAR_ICS_URL_PATH }}
        shell: bash

      - name: Generate docker-compose.yml
        run: |
          envsubst < ${{ env.DOCKER_COMPOSE_PATH }} > ${{ env.DOCKER_COMPOSE_PATH }}.gcp

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ secret.SERVICE }}'
          region: '${{ secret.REGION }}'
          image: '${{ secret.REGION }}-docker.pkg.dev/${{ secret.PROJECT_ID }}/${{ secret.SERVICE }}:latest
